### ISSUE TITLE
Implement the O(N)  approx MEB algorithm specified in the Ivor paper

### ISSUE THREAD

**Issue by Shade5** [Shade5/MEB#5]
Something like the one given here:http://www.siam.org/meetings/alenex03/Abstracts/Pkumar2.PDF
@achyudhk You can try this.

**Comment by achyudh** [comment]
I have been trying to read this paper and alternate ones. The implementation id quite complicated. Been reading the CPP implementation from here: https://people.inf.ethz.ch/gaertner/subdir/software/miniball/Miniball.hpp

There is an alternative, more cited higher dimensional MEB problem solved here: https://people.inf.ethz.ch/gaertner/subdir/software/miniball.html

**Comment by achyudh** [comment]
Yay! Don't need to do this anymore!
